### ISSUE TITLE
Support for TLS certificates in Mosquitto

### ISSUE THREAD

**Issue by pvorb** [t3n/helm-charts#111]
Currenty, the mosquitto helm chart doesn't seem to support providing secrets for certificates, keys and so on that are described in the ["Certificate based SSL/TLS Support" section of the configuration docs](https://mosquitto.org/man/mosquitto-conf-5.html#idm45473494417744).

Are there any plans to support this?

Maybe it would be a good idea to support an arbitrary number of secrets that can be mounted into the file system, so that they can be referenced in the configuration file. This would help when configuring multiple listeners that need different certificates. See https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod for a starting point.

**Comment by helmecke** [comment]
Hi @pvorb, would you like to provide secrets base64 encoded or plain text?

**Comment by pvorb** [comment]
Hi @helmecke, I'm not entirely sure what you mean. The values in a secret are always base64 encoded and will be automatically decoded when mounted into a volume.

Or are you referring to PEM (which is base64 encoded as well) vs some other format? I think PEM is the default for mosquitto and so I think it would be fine if the secret would be of type Opaque and would contain a base64 encoded file (twice in case its a PEM).

**Comment by helmecke** [comment]
You could something like:

```yaml
extraSecret:
  certs:
    cafile: |
      -----BEGIN CERTIFICATE-----
      MIIESjCCAzKgAwIBAgINAeO0mqGNiqmBJWlQuDANBgkqhkiG9w0BAQsFADBMMSAw
      HgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMjETMBEGA1UEChMKR2xvYmFs
      -----END CERTIFICATE-----
```
or provide the secret already base64 encoded

```yaml
extraSecret:
  certs:
    cafile: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVTakNDQXpLZ0F3SUJBZ0lOQWVPMG1
```

**Comment by pvorb** [comment]
Now I get what you're saying.

I was thinking of providing the secret outside of the helm chart and just specifying reference to the secret or other volumes in a more generic way. E.g.:

~~~ yaml
# values.yaml

volumes:
  - mount:
      name: cafile
      mountPath: /opt/mosquitto/
      readOnly: true
    volume:
      name: cafile
      secret:
        secretName: mosquitto-cafile
        items:
        - key: mosquitto-ca
          path: mosquitto-ca
~~~

And then iterating over them via

~~~
          volumeMounts:
{{- range $volume := .Values.volumes }}
            - {{ .mount }}
{{- end }}
      volumes:
{{- range $volume := .Values.volumes }}
        - {{ .volume }}
{{- end }}
~~~

Untested, but I hope you get the idea.

**Comment by pvorb** [comment]
Awesome! Thanks a lot!

This will get into our next sprint, so we won't try this immediately. But it looks very good to me.
