### ISSUE TITLE
snipe-it cannot connect to mysql on fresh install

### ISSUE THREAD

**Issue by bentatham** [t3n/helm-charts#126]
Doing a fresh install of t3n/snipe-it, it cannot connect to mysql:

```
D'oh! Looks like we can't connect to your database. Please update your database settings in your .env file. Your database says: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select 2 + 2)
```
(on /setup landing page)

I have tried playing around with a few things (including adding  values
```
mysql:
  args:
    - "--default-authentication-plugin=mysql_native_password"
```
), but no luck. 

I've tried examining the t3n/mysql chart, and can't figure anything out to make this work.

**Comment by mschmidt291** [comment]
Hi @bentatham.

I now rolled back our MySQL-Chart Version to 5.7.32 which should fix this issue.
