### ISSUE TITLE
Following the instructions on how to use the matomo/stable helm chart displays a missing salt file error. 

### ISSUE THREAD

**Issue by oconnelc** [t3n/helm-charts#146]
Following the instructions located at: https://artifacthub.io/packages/helm/t3n/matomo?modal=install results in the following error message:

`Error: execution error at (matomo/templates/deployment.yaml:59:24): `.Values.salt` is not set.`

The salt appears to be set to blank at: https://github.com/t3n/helm-charts/blob/master/matomo/values.yaml

Running with 

- helm: 3.4.0
- helm repo add t3n https://storage.googleapis.com/t3n-helm-charts
- helm install my-matomo t3n/matomo --version 1.2.1 --namespace ${namespace}

**Comment by mschmidt291** [comment]
Hi @oconnelc 
Thanks for the suggestion. Actually every matomo installation should have a unique key. I now added a default one to the chart, which should be changed in a production environment. The new chart version is now live.
