### ISSUE TITLE
Websocket connection option!!

### ISSUE THREAD

**Issue by puneetmathur-87** [t3n/helm-charts#153]
Team,

I could not find an option in the mosquitto config of the helm charts for enabling the web socket connection to the mqtt server.

**Comment by mschmidt291** [comment]
Websockets are already enabled.

https://github.com/t3n/helm-charts/blob/master/mosquitto/values.yaml#L104

**Comment by puneetmathur-87** [comment]
The web socket is not enabled as a LoadBalancer when I enable in the values. Below is my values file.
resources: 
   limits:
     cpu: 500m
     memory: 4096Mi
   requests:
     cpu: 300m
     memory: 3072Mi
service:
  type: "LoadBalancer"

![image](https://user-images.githubusercontent.com/33253497/122181361-ecf05b00-cea6-11eb-9456-38bd13da68ce.png)

**Comment by puneetmathur-87** [comment]
How we enable the loadbalancer service for the web socket because in the config it is only enabled from the mosquitto config side. The service created doesn't reflect it . Please check below :

helm upgrade  --install mosquitto k8s-at-home/mosquitto --set service.type=LoadBalancer  --version 2.3.0 --dry-run
Release "mosquitto" has been upgraded. Happy Helming!
NAME: mosquitto
LAST DEPLOYED: Wed Jun 16 01:12:42 2021
NAMESPACE: default
STATUS: pending-upgrade
REVISION: 3
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: mosquitto/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    helm.sh/chart: mosquitto-2.3.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
---
# Source: mosquitto/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    helm.sh/chart: mosquitto-2.3.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
---
# Source: mosquitto/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    helm.sh/chart: mosquitto-2.3.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
    spec:

      serviceAccountName: default
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: mosquitto
        image: "eclipse-mosquitto:2.0.7"
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-config
          subPath: mosquitto.conf

        livenessProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
      volumes:
      - configMap:
          name: mosquitto-config
        name: mosquitto-config

NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w mosquitto'
  export SERVICE_IP=$(kubectl get svc --namespace default mosquitto -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo http://$SERVICE_IP:1883

**Comment by mschmidt291** [comment]
@puneetmathur-87 Hm, k8s-at-home is not our repo. You are NOT trying to install our chart.
Please talk to the guys from k8s-at-home.

**Comment by puneetmathur-87** [comment]
I just tried your chart and worked like a charm. Thanks a lot.

**Comment by puneetmathur-87** [comment]
But I am still not able to connect to the websocket on LB IP and port 9090. Is there someone who could help?

**Comment by puneetmathur-87** [comment]
The chart worked well to expose the websocket on LB. But I am still not able to connect to the websocket on LB IP and port 9090. Is there someone who could help?
PUNEET 

    On Wednesday, June 16, 2021, 02:05:06 PM GMT+5:30, Max Schmidt ***@***.***> wrote:  
 
 


@puneetmathur-87 Hm, k8s-at-home is not our repo. You are NOT trying to install our chart.
Please talk to the guys from k8s-at-home.
