### ISSUE TITLE
unms upgrade to 0.1.4

### ISSUE THREAD

**Issue by varac** [t3n/helm-charts#45]
First of all, thx for your unms chart ! I got it working with unms `0.13.3`, which is pinned as default in value.yml.
But this version is already 8 month old and I'd like to use a newer one. However, only changing the image tag to latest release (`0.14.4`) breaks with the following error in the main umns pod:

```
$ node ./cli/migrate.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"
Migration failed: { error: password authentication failed for user "unms"
    at Connection.parseE (/home/app/unms/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/home/app/unms/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/home/app/unms/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I also tried unsuccessfully removing the helm chart completely, and then redeploying with `0.14.4`, to rule out db migration errors, but this is clearly an authentication issue.

Do you have any experiences with upgrading / running a newer version ?

**Comment by mschmidt291** [comment]
Hi Varac,

currently this chart only supports version 0.13.3. With 0.14.X they made UCRM a dependency, which apparently breaks alot. I already opened an issue in the UNMS repo (https://github.com/Ubiquiti-App/UNMS/issues/170)
Feel free to open a PR if you have a solution for fixing this.

**Comment by varac** [comment]
Hi @mschmidt291, that's too bad. I can only second this reply on the upstream issue:

> Personally I don't think it's a good idea to force people to run a full crm platform just to manage their networking equipment

Unfortunately, [ubiquiti's response](https://github.com/Ubiquiti-App/UNMS/issues/170#issuecomment-514140762) is not very helpful and it looks they won't reconsider the hard requirement to their integrated crm :/
So I guess we need to focus on stabilizing it.
For now I'm good with the current version.

Just for my own record, !25 is related to this.

**Comment by varac** [comment]
@mschmidt291 Is there a tracking issue about the unstable UCRM in 0.14 ? Did you open an upstream issue about it or do you have any documentation about what's the issue/ how it breaks ?

**Comment by mschmidt291** [comment]
@varac  So the main problem seems to be postgresql, which UCRM also requires. I opened this issue a while back https://github.com/Ubiquiti-App/UNMS/issues/170 and the answer in short was "UCRM is now integrated with UNMS, so deal with it". Strange thing is, that the docker-compose file runs well, but as soon as I try to integrate UCRM into the helm chart, the error which is described in the issue always comes up.

**Comment by laradji** [comment]
look like UCRM var for POSTGRES don't have the same NAME.

I'm stuck with deploying ucrm with silent error on 
su-exec nginx /usr/src/ucrm/app/console --quiet

For the unms startup i'm stuck here

```
Stepping down from root: su-exec "/usr/local/bin/docker-entrypoint.sh" "index.js"
Running docker-entrypoint index.js
Version: 1.1.6+8b162b691.2020-02-12T13:31:06+01:00
Waiting for database containers
psql: fe_sendauth: no password supplied
Background append only file rewriting started
Restoring backups and/or running migrations
yarn run v1.21.1
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ yarn backup:apply && yarn migrate && yarn check-crm-db
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ node ./cli/apply-backup.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"


```

**Comment by mschmidt291** [comment]
@laradji Is this related to 0.1.4? If not, please open a new issue. For now we won't update this chart to 0.1.4 or above

**Comment by laradji** [comment]
@mschmidt291 yeah its related to the latest version of unms

**Comment by helmecke** [comment]
We deprecated this Chart. There are just to much problems which led us to use VM instead of Kubernetes.
