### ISSUE TITLE
Snipe-IT chart does not work with helm v3.2.1

### ISSUE THREAD

**Issue by tareko** [t3n/helm-charts#70]
Hello friends,

I am using the following command:
```
helm install snipeit t3n/snipeit --set Secret.data.APP_KEY="base64:supersecretkey"
```
and I get the following result:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.APP_KEY
```

This appears to have to do with the chart not being ready for v3.2.x. I'm new to Helm, so haven't had success trying to fix this myself yet.

Any suggestions on how I can troubleshoot this?

tarek : )

**Comment by mschmidt291** [comment]
Hi @tareko I just tried it with 3.2.1 and `helm3 install snipeit t3n/snipeit --set config.snipeit.key="base64:ibNtoKkply8roKip....................="`. Works perfectly fine.

When using Secret.data.APP_KEY, I get the same error message as you. So just use the correct value and it works :)

**Comment by tareko** [comment]
Thank you! That worked. If you have access to the [helm chart in the repository](https://hub.helm.sh/charts/t3n/snipeit/1.0.5), it would be great to update there or to indicate that the instructions for 2.x and 3.x are different.

Thank you!

**Comment by mschmidt291** [comment]
This has nothing to do with Helm 2 or 3. The instructions are correct. You just need to look for the right Chart Version:
https://hub.helm.sh/charts/t3n/snipeit/1.2.6

**Comment by phemmmie** [comment]
I have this same error how do i fix this Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.connection
